---
title: "Proyecto Final del Curso"
---

### **Introducción**

En este proyecto, tendrás la oportunidad de aplicar todos los conocimientos adquiridos a lo largo del curso para resolver un problema real y relevante. El trabajo será desarrollado en equipos de 3 a 5 estudiantes. Además, diseñarás un póster atractivo que resuma tu investigación y crearás una presentación para compartir tus resultados con tus compañeros y la comunidad en general. Los resultados de las investigaciones se mostrarán en la página del Curso para promocionar el talento de los estudiantes de la Escuela de Economía de la UCV.

Este proyecto tiene un peso asignado de 30% sobre el total de la calificación del curso.

La calificación será con un tope de 30 puntos, desagregados de esta manera:

-   5 puntos: originalidad y claridad del proyecto (identificación problema, plantear una pregunta de investigación).

-   5 puntos: calidad del código (limpieza datos, procesamiento, análisis exploratorio)

-   5 puntos: comunicación de los resultados (gráficos, reporte quarto)

-   5 puntos: presentación en público del proyecto

-   5 puntos póster (afiche)

-   5 puntos resto: (documentar proceso, compartir proyecto)

### **Objetivos del Proyecto**

-   **Investigación:** Realiza un análisis de datos exhaustivo, utilizando las técnicas aprendidas en clase.

-   **Obteneción y limpiar los datos:** Recolectar los datos necesarios y realizar las tareas de limpieza y transformación requeridas.

-   **Realizar el análisis exploratorio de datos:** Explorar los datos para identificar patrones, tendencias y relaciones entre las variables.

-   **Modelar los datos:** Aplicar técnicas de modelado adecuadas para responder a la pregunta de investigación (opcional, es un valor agregado, no es necesario).

-   **Visualizar los resultados:** Crear visualizaciones claras y efectivas para comunicar los hallazgos.

-   **Comunicación efectiva:** Diseña un póster visualmente atractivo que comunique de manera clara y concisa los objetivos, metodología, resultados y conclusiones de tu investigación.

-   **Documentar el proceso:** Elaborar un informe que describa cada una de las etapas del proyecto, incluyendo el código utilizado.

-   **Presentación en público:** Prepara una presentación breve para exponer tu proyecto ante tus compañeros y recibir retroalimentación.

-   **Colaboración:** Comparte tu trabajo con la comunidad del curso, contribuyendo a un repositorio de proyectos.

-   **Compartir el proyecto:** Crear un repositorio en una plataforma de control de versiones ( GitHub) para compartir el código y los resultados con otros.

### **Especificaciones del Proyecto**

-   **Contenido:** El proyecto debe abordar distintas herramientas de R aprendidas hasta el momento.

-   **Tema:** Elige un tema de tu interés relacionado con Venezuela que pueda ser abordado con los datos disponibles (obligatorio).

-   **Calidad del código:** Se evaluará la claridad, eficiencia y organización del código.

-   **Estructura:** El proyecto debe seguir las buenas prácticas de desarrollo en RStudio, incluyendo la organización de archivos, el uso de funciones y la documentación del código.

-   **Póster:** Diseña un póster que incluya los siguientes elementos: título, introducción, objetivos, metodología, resultados (visualizaciones), conclusiones y referencias.

-   **Presentación:** Prepara una presentación de 5-7 minutos para exponer tu proyecto.

-   **Informe:** Entrega un informe escrito que detalle el proceso de investigación, los resultados y las conclusiones (opcional).

-   **Reproducibilidad:** El proyecto debe ser reproducible, es decir, cualquier persona con los mismos datos y el código fuente debería obtener los mismos resultados (opcional, es un valor agregado).

-   **Comunicación:** Los resultados deben ser presentados de manera clara y concisa, utilizando gráficos, tablas y texto explicativo.

-   **Repositorio:** Comparte tu código y los datos en un repositorio en línea (por ejemplo, GitHub).

### **Sugerencias de Temas**

-   Se abordará en clase al momento de asignar el proyecto y los grupos.

### **Entrega:**

-   **Informe:** Un documento que describa el problema, la metodología utilizada, los resultados y las conclusiones (opcional).

-   **Código Carpeta Proyecto:** El código R utilizado para realizar el análisis.

-   **Presentación:** Una presentación breve que resuma los principales hallazgos del proyecto.

-   **Repositorio:** Un enlace al repositorio en GitHub o una plataforma similar.

-   **Póster- Afiche:** lámina (dimensiones por definir) con lo indicado anteriormente

### Fecha Entrega:

Semana final del Curso (fecha precisa por definir).
