---
title: "Proyecto Mitad del Curso"
---

### **Introducción**

En esta etapa de l curso, pondrás en práctica los conocimientos adquiridos hasta ahora en R para abordar un **problema real**. El trabajo será desarrollado en equipos de 3 a 5 estudiantes. La idea es que desarrolles un proyecto completo, desde la definición del problema hasta la presentación de los resultados. Este proyecto tiene un peso asignado de 20% sobre el total de la calificación del curso.

La calificación será con un tope de 20 puntos, desagregados de esta manera:

-   5 puntos: originalidad y claridad del proyecto (identificación problema, plantear una pregunta de investigación).

-   5 puntos: calidad del código (limpieza datos, procesamiento, análisis exploratorio)

-   5 puntos: comunicación de los resultados (gráficos, reporte quarto)

-   5 puntos resto: (documentar proceso, compartir proyecto)

### **Objetivos del Proyecto**

-   **Identificar un problema:** Seleccionar un problema relevante y actual, preferiblemente relacionado con Venezuela, que pueda ser analizado con los datos disponibles.

-   **Plantear una pregunta de investigación:** Formular una pregunta clara y concisa que el proyecto buscará responder.

-   **Obteneción y limpiar los datos:** Recolectar los datos necesarios y realizar las tareas de limpieza y transformación requeridas.

-   **Realizar el análisis exploratorio de datos:** Explorar los datos para identificar patrones, tendencias y relaciones entre las variables.

-   **Modelar los datos:** Aplicar técnicas de modelado adecuadas para responder a la pregunta de investigación (opcional, es un valor agregado, no es necesario).

-   **Visualizar los resultados:** Crear visualizaciones claras y efectivas para comunicar los hallazgos.

-   **Documentar el proceso:** Elaborar un informe que describa cada una de las etapas del proyecto, incluyendo el código utilizado.

-   **Compartir el proyecto:** Crear un repositorio en una plataforma de control de versiones (GitHub) para compartir el código y los resultados con otros. (opcional, es un valor agregado)

### **Especificaciones del Proyecto**

-   **Contenido:** El proyecto debe abordar distintas herramientas de R aprendidas hasta el momento.

-   **Calidad del código:** Se evaluará la claridad, eficiencia y organización del código.

-   **Estructura:** El proyecto debe seguir las buenas prácticas de desarrollo en RStudio, incluyendo la organización de archivos, el uso de funciones y la documentación del código.

-   **Reproducibilidad:** El proyecto debe ser reproducible, es decir, cualquier persona con los mismos datos y el código fuente debería obtener los mismos resultados (opcional, es un valor agregado).

-   **Comunicación:** Los resultados deben ser presentados de manera clara y concisa, utilizando gráficos, tablas y texto explicativo.

### **Sugerencias de Temas**

-   Se abordará en clase al momento de asignar el proyecto y los grupos.

### **Entrega**

El proyecto final deberá entregarse en un formato reproducible (por ejemplo, un archivo Quarto), incluyendo:

-   **Informe:** Un documento que describa el problema, la metodología utilizada, los resultados y las conclusiones (opcional).

-   **Código Carpeta Proyecto:** El código R utilizado para realizar el análisis.

-   **Presentación:** Una presentación breve que resuma los principales hallazgos del proyecto.

-   **Repositorio (opcional):** Un enlace al repositorio en GitHub o una plataforma similar.

    ### Fecha Entrega:

    Semana intermedia del Curso (fecha precisa por definir).
